// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8avVoOMHX4eNkXtRAaUnRXffZoj8sLLA',
    appId: '1:355986097553:web:6b3cf1e6e68a2c8e19c630',
    messagingSenderId: '355986097553',
    projectId: 'emailpassform',
    authDomain: 'emailpassform.firebaseapp.com',
    storageBucket: 'emailpassform.appspot.com',
    measurementId: 'G-ECYWZL8JQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7HNUb5XuwhVVzElUWjCXf5fxpERvYYN4',
    appId: '1:355986097553:android:904c4776eeaca6bd19c630',
    messagingSenderId: '355986097553',
    projectId: 'emailpassform',
    storageBucket: 'emailpassform.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtVNPn3pe11VkZhLKT9ByxwayZlXqkkTg',
    appId: '1:355986097553:ios:20f30f44cc59b88219c630',
    messagingSenderId: '355986097553',
    projectId: 'emailpassform',
    storageBucket: 'emailpassform.appspot.com',
    iosBundleId: 'com.example.regLogForm',
  );
}
